### ISSUE TITLE
Hello again!

### ISSUE THREAD

**Issue by iamtheblackunicorn** [iamtheblackunicorn/Cobra#1]
@xcodz-dot Hello, again! HexLang lives again but this time as a snake. :snake:

**Comment by xcodz-dot** [comment]
oh great.

**Comment by xcodz-dot** [comment]
so did you delete your old account and created this one or are you a different user?

**Comment by iamtheblackunicorn** [comment]
@xcodz-dot I deleted my old one and made a new one. Is there somewhere where we can chat privately? Because I have a suggestion.

**Comment by xcodz-dot** [comment]
> @xcodz-dot I deleted my old one and made a new one. Is there somewhere where we can chat privately? Because I have a suggestion.

I do not really know any such place but I will make a private repo and send you the collaboration request their we can start talk in a issue

**Comment by iamtheblackunicorn** [comment]
Ok, sounds great, let's do that! ;) @xcodz-dot
